name: CI

on:
  workflow_dispatch: # This allows you to manually run the workflow from GitHub's web UI
  pull_request:
    branches: [ '*' ] # This means this workflow will run when any PR is created or any changes are pushed to a PR, on any branch

jobs:

  test_xcode12_ios14:
    name: Run tests on Xcode 13 and iOS 15
    runs-on: macOS-11

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Xcode version to 13
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Build for testing
        run: xcodebuild build-for-testing -workspace Example/PixelTest.xcworkspace -scheme PixelTest-Example -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0'
      - name: Test on iPhone 13
        run: xcodebuild test-without-building -workspace Example/PixelTest.xcworkspace -scheme PixelTest-Example -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0'
          
  build_spm:
    name: Ensure Swift Package Manager builds
    runs-on: macOS-11

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Xcode version to 13
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Build Swift Package Manager
        run: xcodebuild -workspace package.xcworkspace -scheme PixelTest -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0'

  build_carthage:
    name: Ensure Carthage builds
    runs-on: macOS-11

    steps:
      - name: Set Xcode version to 13
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Build Carthage
        run: ./carthage.sh build --archive

  build_cocoapods:
    name: Ensure Cocoapods builds
    runs-on: macOS-11

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Xcode version to 13
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Build Cocoapods
        run: pod lib lint --verbose --allow-warnings
